import { Edge, Node } from '@xyflow/react';

type CustomNodeData = {
    label: string;
};

// Nodes for the iOS roadmap
export const IOSNodes: Node<Partial<CustomNodeData>>[] = [
    // Programming Languages Node (Central Node)
    {
        id: 'languages',
        position: { x: 400, y: 50 },
        data: { label: 'Programming Languages' },
        style: {
            background: '#FF9E3B',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #E86C00',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // Programming Languages subnodes
    {
        id: 'swift',
        position: { x: 700, y: 0 },
        data: { label: 'Swift' },
        style: {
            background: '#FFD166',
            border: '2px solid #FF9E3B',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'objc',
        position: { x: 700, y: 80 },
        data: { label: 'Objective-C' },
        style: {
            background: '#FFD166',
            border: '2px solid #FF9E3B',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    // iOS Frameworks Node
    {
        id: 'ios-frameworks',
        position: { x: 400, y: 200 },
        data: { label: 'iOS Frameworks' },
        style: {
            background: '#06D6A0',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #048A81',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // iOS Frameworks subnodes
    {
        id: 'uikit',
        position: { x: 150, y: 150 },
        data: { label: 'UIKit' },
        style: {
            background: '#83E8BA',
            border: '2px solid #06D6A0',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'swiftui',
        position: { x: 150, y: 230 },
        data: { label: 'SwiftUI' },
        style: {
            background: '#83E8BA',
            border: '2px solid #06D6A0',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'foundation',
        position: { x: 150, y: 310 },
        data: { label: 'Foundation' },
        style: {
            background: '#83E8BA',
            border: '2px solid #06D6A0',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    // UI Design Node
    {
        id: 'ui-design',
        position: { x: 400, y: 350 },
        data: { label: 'UI Design' },
        style: {
            background: '#118AB2',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #073B4C',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // UI Design subnodes
    {
        id: 'storyboards',
        position: { x: 700, y: 300 },
        data: { label: 'Storyboards' },
        style: {
            background: '#A2D7F5',
            border: '2px solid #118AB2',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'xibs',
        position: { x: 700, y: 380 },
        data: { label: 'XIBs' },
        style: {
            background: '#A2D7F5',
            border: '2px solid #118AB2',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'human-guidelines',
        position: { x: 700, y: 460 },
        data: { label: 'Human Interface Guidelines' },
        style: {
            background: '#A2D7F5',
            border: '2px solid #118AB2',
            borderRadius: 12,
            padding: 12,
            width: 200,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    // Data Persistence Node
    {
        id: 'data-persistence',
        position: { x: 400, y: 500 },
        data: { label: 'Data Persistence' },
        style: {
            background: '#EF476F',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #9E0059',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // Data Persistence subnodes
    {
        id: 'core-data',
        position: { x: 150, y: 450 },
        data: { label: 'Core Data' },
        style: {
            background: '#FFA8C2',
            border: '2px solid #EF476F',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'realm',
        position: { x: 150, y: 530 },
        data: { label: 'Realm' },
        style: {
            background: '#FFA8C2',
            border: '2px solid #EF476F',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'cloudkit',
        position: { x: 150, y: 610 },
        data: { label: 'CloudKit' },
        style: {
            background: '#FFA8C2',
            border: '2px solid #EF476F',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    // APIs Node
    {
        id: 'apis',
        position: { x: 400, y: 650 },
        data: { label: 'APIs' },
        style: {
            background: '#7209B7',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #3A0CA3',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // APIs subnodes
    {
        id: 'rest-api',
        position: { x: 700, y: 600 },
        data: { label: 'REST APIs' },
        style: {
            background: '#C77DFF',
            border: '2px solid #7209B7',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'alamofire',
        position: { x: 700, y: 680 },
        data: { label: 'Alamofire' },
        style: {
            background: '#C77DFF',
            border: '2px solid #7209B7',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'urlsession',
        position: { x: 700, y: 760 },
        data: { label: 'URLSession' },
        style: {
            background: '#C77DFF',
            border: '2px solid #7209B7',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    // Architecture Node
    {
        id: 'architecture',
        position: { x: 400, y: 800 },
        data: { label: 'Architecture' },
        style: {
            background: '#F72585',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #B5179E',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // Architecture subnodes
    {
        id: 'mvc',
        position: { x: 150, y: 750 },
        data: { label: 'MVC' },
        style: {
            background: '#FF8FAB',
            border: '2px solid #F72585',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'mvvm',
        position: { x: 150, y: 830 },
        data: { label: 'MVVM' },
        style: {
            background: '#FF8FAB',
            border: '2px solid #F72585',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'viper',
        position: { x: 150, y: 910 },
        data: { label: 'VIPER' },
        style: {
            background: '#FF8FAB',
            border: '2px solid #F72585',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    // Testing Node
    {
        id: 'testing',
        position: { x: 400, y: 950 },
        data: { label: 'Testing' },
        style: {
            background: '#4CC9F0',
            padding: 15,
            borderRadius: 16,
            border: '3px solid #4895EF',
            fontWeight: 'bold',
            boxShadow: '4px 4px 8px rgba(0,0,0,0.2)',
            textAlign: 'center',
            width: 220,
            fontSize: '1.1rem',
            color: '#fff',
        },
    },
    // Testing subnodes
    {
        id: 'xctest',
        position: { x: 700, y: 900 },
        data: { label: 'XCTest' },
        style: {
            background: '#B8F2FF',
            border: '2px solid #4CC9F0',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'xcuitest',
        position: { x: 700, y: 980 },
        data: { label: 'XCUITest' },
        style: {
            background: '#B8F2FF',
            border: '2px solid #4CC9F0',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
    {
        id: 'quick-nimble',
        position: { x: 700, y: 1060 },
        data: { label: 'Quick/Nimble' },
        style: {
            background: '#B8F2FF',
            border: '2px solid #4CC9F0',
            borderRadius: 12,
            padding: 12,
            width: 180,
            textAlign: 'center',
            boxShadow: '2px 2px 6px rgba(0,0,0,0.1)',
            fontWeight: '600',
        },
    },
];

// Edges for the iOS roadmap
export const IOSEdges: Edge[] = [
    // Languages to subnodes
    {
        id: 'e-languages-swift',
        source: 'languages',
        target: 'swift',
        type: 'smoothstep',
        style: {
            stroke: '#FF9E3B',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-languages-objc',
        source: 'languages',
        target: 'objc',
        type: 'smoothstep',
        style: {
            stroke: '#FF9E3B',
            strokeWidth: 3,
        },
        animated: true,
    },
    // Languages to iOS Frameworks
    {
        id: 'e-languages-ios-frameworks',
        source: 'languages',
        target: 'ios-frameworks',
        type: 'smoothstep',
        style: {
            stroke: '#FF9E3B',
            strokeWidth: 3,
        },
        animated: true,
    },
    // iOS Frameworks to subnodes
    {
        id: 'e-ios-frameworks-uikit',
        source: 'ios-frameworks',
        target: 'uikit',
        type: 'smoothstep',
        style: {
            stroke: '#06D6A0',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-ios-frameworks-swiftui',
        source: 'ios-frameworks',
        target: 'swiftui',
        type: 'smoothstep',
        style: {
            stroke: '#06D6A0',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-ios-frameworks-foundation',
        source: 'ios-frameworks',
        target: 'foundation',
        type: 'smoothstep',
        style: {
            stroke: '#06D6A0',
            strokeWidth: 3,
        },
        animated: true,
    },
    // iOS Frameworks to UI Design
    {
        id: 'e-ios-frameworks-ui-design',
        source: 'ios-frameworks',
        target: 'ui-design',
        type: 'smoothstep',
        style: {
            stroke: '#06D6A0',
            strokeWidth: 3,
        },
        animated: true,
    },
    // UI Design to subnodes
    {
        id: 'e-ui-design-storyboards',
        source: 'ui-design',
        target: 'storyboards',
        type: 'smoothstep',
        style: {
            stroke: '#118AB2',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-ui-design-xibs',
        source: 'ui-design',
        target: 'xibs',
        type: 'smoothstep',
        style: {
            stroke: '#118AB2',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-ui-design-human-guidelines',
        source: 'ui-design',
        target: 'human-guidelines',
        type: 'smoothstep',
        style: {
            stroke: '#118AB2',
            strokeWidth: 3,
        },
        animated: true,
    },
    // UI Design to Data Persistence
    {
        id: 'e-ui-design-data-persistence',
        source: 'ui-design',
        target: 'data-persistence',
        type: 'smoothstep',
        style: {
            stroke: '#118AB2',
            strokeWidth: 3,
        },
        animated: true,
    },
    // Data Persistence to subnodes
    {
        id: 'e-data-persistence-core-data',
        source: 'data-persistence',
        target: 'core-data',
        type: 'smoothstep',
        style: {
            stroke: '#EF476F',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-data-persistence-realm',
        source: 'data-persistence',
        target: 'realm',
        type: 'smoothstep',
        style: {
            stroke: '#EF476F',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-data-persistence-cloudkit',
        source: 'data-persistence',
        target: 'cloudkit',
        type: 'smoothstep',
        style: {
            stroke: '#EF476F',
            strokeWidth: 3,
        },
        animated: true,
    },
    // Data Persistence to APIs
    {
        id: 'e-data-persistence-apis',
        source: 'data-persistence',
        target: 'apis',
        type: 'smoothstep',
        style: {
            stroke: '#EF476F',
            strokeWidth: 3,
        },
        animated: true,
    },
    // APIs to subnodes
    {
        id: 'e-apis-rest-api',
        source: 'apis',
        target: 'rest-api',
        type: 'smoothstep',
        style: {
            stroke: '#7209B7',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-apis-alamofire',
        source: 'apis',
        target: 'alamofire',
        type: 'smoothstep',
        style: {
            stroke: '#7209B7',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-apis-urlsession',
        source: 'apis',
        target: 'urlsession',
        type: 'smoothstep',
        style: {
            stroke: '#7209B7',
            strokeWidth: 3,
        },
        animated: true,
    },
    // APIs to Architecture
    {
        id: 'e-apis-architecture',
        source: 'apis',
        target: 'architecture',
        type: 'smoothstep',
        style: {
            stroke: '#7209B7',
            strokeWidth: 3,
        },
        animated: true,
    },
    // Architecture to subnodes
    {
        id: 'e-architecture-mvc',
        source: 'architecture',
        target: 'mvc',
        type: 'smoothstep',
        style: {
            stroke: '#F72585',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-architecture-mvvm',
        source: 'architecture',
        target: 'mvvm',
        type: 'smoothstep',
        style: {
            stroke: '#F72585',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-architecture-viper',
        source: 'architecture',
        target: 'viper',
        type: 'smoothstep',
        style: {
            stroke: '#F72585',
            strokeWidth: 3,
        },
        animated: true,
    },
    // Architecture to Testing
    {
        id: 'e-architecture-testing',
        source: 'architecture',
        target: 'testing',
        type: 'smoothstep',
        style: {
            stroke: '#F72585',
            strokeWidth: 3,
        },
        animated: true,
    },
    // Testing to subnodes
    {
        id: 'e-testing-xctest',
        source: 'testing',
        target: 'xctest',
        type: 'smoothstep',
        style: {
            stroke: '#4CC9F0',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-testing-xcuitest',
        source: 'testing',
        target: 'xcuitest',
        type: 'smoothstep',
        style: {
            stroke: '#4CC9F0',
            strokeWidth: 3,
        },
        animated: true,
    },
    {
        id: 'e-testing-quick-nimble',
        source: 'testing',
        target: 'quick-nimble',
        type: 'smoothstep',
        style: {
            stroke: '#4CC9F0',
            strokeWidth: 3,
        },
        animated: true,
    },
];
