export const Routes = {
    home: '/',
    login: '/login',
    register: '/register',
    more: '/customer/more',
    test: '/customer/test',
    process: '/customer/process',
    project: '/customer/project',
    upgrade: '/customer/upgrade',
    payment: '/customer/payment',
    profile: '/customer/profile',
    history: '/customer/history',
    testdetail: '/customer/testdetail',
    testresult: '/customer/result',
    challenge: '/customer/challenge',
};
